name: 'Markdown Code Embed'
description: Embeds code into README with MDCE
branding:
  color: purple
  icon: file-text

on: 
  workflow_dispatch:
  pull_request:
    branches: 
      - main
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Run MDCE
        run: ./mdce.py -q
